fprintf('\nBottle Fill Only,\n\n')
fprintf('Bottle Fill Only, Bottle Fill Only Bottle Fill Only! Bottle Fill Only. Bottle Fill Only? \n')
fprintf('Bottle Fill Only Bottle Fill Only Bottle Fill Only Bottle Fill Only Bottle Fill Only \n')
fprintf('Bottle Fill Only Bottle Fill Only! Bottle Fill Only Bottle Fill Only Bottle Fill Only.\n')
fprintf('\nBottle Fill Only,\n')
fprintf('Bottle Fill Only Bottle Fill Only.\n')
